package db

// auditColumnReview lists every column of every audited table and what the
// history does with it: "record" it, "mask" it (bank accounts) or "skip" it
// (bookkeeping, blobs, secrets). A column added to one of these tables fails
// TestAuditColumnsAreReviewed until it is listed here, so a new secret can't
// slip into a history kept for two years. Same check as STBvirement's.
var auditColumnReview = map[string]map[string]string{
	"accounts":            {"id": "skip", "organizationId": "skip", "parentId": "record", "code": "record", "name": "record", "type": "record", "isGroup": "record", "isActive": "record", "datevAccountNumber": "record", "description": "record", "createdAt": "skip"},
	"clients":             {"id": "skip", "organizationId": "skip", "name": "record", "emails": "record", "phone": "record", "website": "record", "registration_number": "record", "vatin": "record", "createdAt": "skip", "code": "record", "street": "record", "house_number": "record", "postal_code": "record", "city": "record", "country_code": "record", "tax_number": "record", "default_buyer_reference": "record", "defaultCurrency": "record", "identity_number": "record", "iban": "mask", "phone2": "record", "phone3": "record", "guarantor": "record", "address": "record", "importBatchId": "record"},
	"fiscal_periods":      {"id": "skip", "organizationId": "skip", "fiscalYearId": "record", "name": "record", "startDate": "record", "endDate": "record", "status": "record", "closedAt": "record", "createdAt": "skip"},
	"fiscal_years":        {"id": "skip", "organizationId": "skip", "name": "record", "startDate": "record", "endDate": "record", "status": "record", "lockDate": "record", "closedAt": "record", "createdAt": "skip"},
	"imports":             {"id": "skip", "organizationId": "skip", "importNumber": "record", "date": "record", "currency": "record", "exchangeRate": "record", "exchangeRateDate": "record", "freightCost": "record", "customsCost": "record", "notes": "record", "createdAt": "skip", "serialNumberPrefix": "record", "serialNumberRangeStart": "record", "serialNumberRangeEnd": "record"},
	"inbound_deliveries":  {"id": "skip", "organizationId": "skip", "purchaseOrderId": "record", "vendorId": "record", "deliveryNumber": "record", "deliveryDate": "record", "vendorDeliveryNote": "record", "trackingNumber": "record", "notes": "record", "status": "record", "createdAt": "skip", "currency": "record", "exchangeRate": "record", "exchangeRateDate": "record"},
	"incoming_invoices":   {"id": "skip", "organizationId": "skip", "vendorId": "record", "purchaseOrderId": "record", "vendorInvoiceNumber": "record", "reference": "record", "state": "record", "date": "record", "dueDate": "record", "currency": "record", "notes": "record", "total": "record", "taxTotal": "record", "subTotal": "record", "matchOverride": "record", "matchOverrideReason": "record", "createdAt": "skip", "exchangeRate": "record", "exchangeRateDate": "record"},
	"invoices":            {"id": "skip", "organizationId": "skip", "number": "record", "state": "record", "clientId": "record", "date": "record", "dueDate": "record", "currency": "record", "customerNotes": "record", "createdAt": "skip", "total": "record", "taxTotal": "record", "subTotal": "record", "overdueCharge": "record", "buyerReference": "record", "paymentTerms": "record", "exchangeRate": "record", "exchangeRateDate": "record", "fiscalStampAmount": "record", "withholdingTaxRate": "record", "withholdingTaxAmount": "record", "discountAmount": "record", "movesStock": "record", "origin": "record", "importBatchId": "record"},
	"journal_entries":     {"id": "skip", "organizationId": "skip", "journalId": "record", "fiscalYearId": "record", "fiscalPeriodId": "record", "entryNumber": "record", "date": "record", "reference": "record", "description": "record", "sourceDocumentType": "record", "sourceDocumentId": "record", "status": "record", "reversalOfEntryId": "record", "reversalReason": "record", "postedAt": "record", "createdBy": "record", "createdAt": "skip"},
	"journals":            {"id": "skip", "organizationId": "skip", "code": "record", "name": "record", "type": "record", "isSystem": "record", "createdAt": "skip"},
	"orders":              {"id": "skip", "organizationId": "skip", "clientId": "record", "orderNumber": "record", "status": "record", "orderDate": "record", "deliveryDate": "record", "shippingAddress": "record", "trackingNumber": "record", "notes": "record", "createdAt": "skip", "currency": "record", "exchangeRate": "record", "exchangeRateDate": "record"},
	"organizations":       {"id": "skip", "name": "record", "country": "record", "email": "record", "phone": "record", "website": "record", "registration_number": "record", "vatin": "record", "bank_name": "record", "iban": "mask", "currency": "record", "minimum_fraction_digits": "record", "due_days": "record", "customerNotes": "record", "createdAt": "skip", "logo": "skip", "invoice_number_format": "record", "invoice_number_counter": "record", "overdueCharge": "record", "date_format": "record", "code": "record", "match_price_tolerance_percent": "record", "match_quantity_tolerance_percent": "record", "bic": "record", "tax_number": "record", "street": "record", "house_number": "record", "postal_code": "record", "city": "record", "country_code": "record", "defaultArAccountId": "record", "defaultApAccountId": "record", "defaultRevenueAccountId": "record", "defaultExpenseAccountId": "record", "defaultCashAccountId": "record", "fxGainAccountId": "record", "fxLossAccountId": "record", "retainedEarningsAccountId": "record", "datevClearingAccountId": "record", "datev_consultant_number": "record", "datev_client_number": "record", "defaultInventoryAccountId": "record", "defaultGRNIAccountId": "record", "defaultCOGSAccountId": "record", "defaultInventoryAdjustmentAccountId": "record", "brandColor": "record", "defaultFiscalStampAmount": "record", "defaultStampDutyAccountId": "record", "documentLayout": "record", "fiscalStampEnabled": "record", "withholdingTaxEnabled": "record", "defaultImportCostsPayableAccountId": "record", "defaultCashRegisterAccountId": "record", "amountInWordsEnabled": "record", "documentLanguage": "record", "timezone": "record", "inventoryValuation": "record", "isTest": "record", "masterDataSummaries": "record"},
	"outbound_deliveries": {"id": "skip", "organizationId": "skip", "orderId": "record", "deliveryNumber": "record", "deliveryDate": "record", "shippingAddress": "record", "trackingNumber": "record", "notes": "record", "status": "record", "createdAt": "skip", "clientId": "record"},
	"payment_terms":       {"id": "skip", "organizationId": "skip", "name": "record", "isDefault": "record", "createdAt": "skip"},
	"payments":            {"id": "skip", "organizationId": "skip", "direction": "record", "clientId": "record", "vendorId": "record", "bankAccountId": "record", "amount": "record", "currency": "record", "exchangeRate": "record", "exchangeRateDate": "record", "date": "record", "method": "record", "reference": "record", "notes": "record", "status": "record", "journalEntryId": "record", "voidingEntryId": "record", "createdAt": "skip", "origin": "record"},
	"product_families":    {"id": "skip", "organizationId": "skip", "name": "record", "createdAt": "skip"},
	"production_orders":   {"id": "skip", "organizationId": "skip", "orderNumber": "record", "status": "record", "finishedProductId": "record", "finishedProductName": "record", "quantity": "record", "date": "record", "importId": "record", "notes": "record", "createdAt": "skip"},
	"products":            {"id": "skip", "organizationId": "skip", "name": "record", "description": "record", "sku": "record", "price": "record", "unitCost": "record", "unit": "record", "type": "record", "taxRateId": "record", "createdAt": "skip", "stockEnabled": "record", "stockQuantity": "record", "serialized": "record", "revenueAccountId": "record", "expenseAccountId": "record", "category": "record", "unitOfMeasureId": "record", "familyId": "record"},
	"purchase_orders":     {"id": "skip", "organizationId": "skip", "vendorId": "record", "orderNumber": "record", "status": "record", "orderDate": "record", "expectedDate": "record", "currency": "record", "deliveryAddress": "record", "notes": "record", "createdAt": "skip", "exchangeRate": "record", "exchangeRateDate": "record", "importId": "record"},
	"taxRates":            {"id": "skip", "organizationId": "skip", "name": "record", "description": "record", "percentage": "record", "isDefault": "record", "category_code": "record", "exemption_reason": "record", "outputTaxAccountId": "record", "inputTaxAccountId": "record", "datev_bu_key": "record"},
	"units_of_measure":    {"id": "skip", "organizationId": "skip", "name": "record", "isDefault": "record", "createdAt": "skip"},
	"users":               {"id": "skip", "email": "record", "passwordHash": "skip", "displayName": "record", "role": "record", "isActive": "record", "createdAt": "skip", "lastLoginAt": "record", "isPlatformAdmin": "record", "tokenVersion": "skip"},
	"vendors":             {"id": "skip", "organizationId": "skip", "name": "record", "code": "record", "emails": "record", "phone": "record", "website": "record", "registration_number": "record", "vatin": "record", "defaultCurrency": "record", "paymentTermsDays": "record", "createdAt": "skip", "street": "record", "house_number": "record", "postal_code": "record", "city": "record", "country_code": "record"},
}
